EMAIL_TOOL_DECLARATIONS = [
    {"name": "get_emails", "description": "Gmail hesabında email axtarır və uyğun mesajların göndərən, mövzu, tarix və qısa məzmununu qaytarır. Qovluq sorğularında folder parametrini istifadə et: inbox, sent, drafts, spam, trash, promotions, social, updates, purchases, starred, all_mail.", "parameters": {"type": "OBJECT", "properties": {"query": {"type": "STRING"}, "folder": {"type": "STRING"}, "limit": {"type": "NUMBER"}}}},
    {"name": "read_email_thread", "description": "Gmail thread-dəki bütün mesajları oxuyur.", "parameters": {"type": "OBJECT", "properties": {"thread_id": {"type": "STRING"}}, "required": ["thread_id"]}},
    {"name": "prepare_trash_emails", "description": "Gmail email(lər)ini Trash-a göndərmək üçün snapshot hazırlayır. Heç nə silmir; açıq təsdiq tələb edir.", "parameters": {"type": "OBJECT", "properties": {"folder": {"type": "STRING"}, "message_id": {"type": "STRING"}, "query": {"type": "STRING"}}}},
    {"name": "trash_emails", "description": "Yalnız əvvəlki açıq təsdiqdən sonra snapshot-ı Trash-a göndərir. confirmation_id təsdiqlənmiş əməliyyatı müəyyən edir.", "parameters": {"type": "OBJECT", "properties": {"confirmation_id": {"type": "STRING"}}, "required": ["confirmation_id"]}},
    {"name": "read_email", "description": "Gmail-da message_id ilə konkret emaili oxuyur.", "parameters": {"type": "OBJECT", "properties": {"message_id": {"type": "STRING"}}, "required": ["message_id"]}},
    {"name": "prepare_email_reply", "description": "Mövcud Gmail emailinə cavab hazırlayır və Draft yaradır. Göndərilmir; sonrakı göndəriş üçün açıq təsdiq tələb olunur.", "parameters": {"type": "OBJECT", "properties": {"message_id": {"type": "STRING"}, "body": {"type": "STRING"}}, "required": ["message_id", "body"]}},
    {"name": "prepare_new_email", "description": "Yeni Gmail Draft yaradır. Göndərilmir; sonrakı göndəriş üçün açıq təsdiq tələb olunur.", "parameters": {"type": "OBJECT", "properties": {"to": {"type": "STRING"}, "subject": {"type": "STRING"}, "body": {"type": "STRING"}, "cc": {"type": "STRING"}, "bcc": {"type": "STRING"}}, "required": ["to", "subject", "body"]}},
    {"name": "send_email", "description": "Gmail Draft-ı göndərir. Yalnız istifadəçi açıq şəkildə təsdiqlədikdən sonra çağırılmalıdır; confirmation_id həmin təsdiqi bağlayır.", "parameters": {"type": "OBJECT", "properties": {"draft_id": {"type": "STRING"}, "confirmation_id": {"type": "STRING"}}, "required": ["draft_id"]}},
    {"name": "sync_google_contacts", "description": "Google Contacts-dakı kontaktları VICTOR-un SQL kontakt bazası ilə sinxronizasiya edir.", "parameters": {"type": "OBJECT", "properties": {}}}
]
